/**
 * Estado en memoria compartido entre servicios (sin base de datos).
 * Cada servicio importa este módulo para lecturas/escrituras consistentes
 * (obras, personal, asistencias, etc.). Cuando exista API, sustituir por llamadas HTTP.
 */

export const store = {
  nextIds: {
    obra: 7,
    personal: 13,
    usuario: 9,
    dispositivo: 4,
    asistencia: 9,
    documento: 7,
  },
  obras: [
    {
      id: 1,
      codigo: "26IBG03",
      nombre: "Mandarino",
      ubicacion: "Ibagué",
      encargado: "Mauricio Javier Torres",
      fechaInicio: "2024-01-15",
      estado: "activa",
      presente: 0,
      pendientes: [
        "Permiso Médico — Julio Sanchez",
        "Nueva Asistencia Registrada — Hacienda Peñalisa",
      ],
    },
    {
      id: 2,
      codigo: "08001",
      nombre: "Edificio Torre Central",
      ubicacion: "Bogotá",
      encargado: "Sandra Milena García",
      fechaInicio: "2024-02-01",
      estado: "activa",
      presente: 0,
      pendientes: ["Pendiente validación de ingreso — Felipe Ríos"],
    },
    {
      id: 3,
      codigo: "08004",
      nombre: "Bodega Industrial Sur",
      ubicacion: "Bogotá",
      encargado: "Oscar Gomez Estrada",
      fechaInicio: "2023-08-01",
      estado: "finalizada",
      presente: 0,
      pendientes: [],
    },
    {
      id: 4,
      codigo: "08005",
      nombre: "Hospital Regional",
      ubicacion: "Bucaramanga",
      encargado: "Claudia Yulieth Faca",
      fechaInicio: "2024-03-10",
      estado: "suspendida",
      presente: 0,
      pendientes: ["Actualización de plan SST requerida"],
    },
    {
      id: 5,
      nombre: "H. Peñalisa",
      codigo: "08006",
      ubicacion: "Ibagué",
      encargado: "Mauricio Javier Torres",
      fechaInicio: "2023-10-01",
      estado: "activa",
      presente: 0,
      pendientes: [],
    },
    {
      id: 6,
      codigo: "08007",
      nombre: "H. Nakare",
      ubicacion: "Bogotá, Suba",
      encargado: "Mauricio Javier Torres",
      fechaInicio: "2024-03-10",
      estado: "activa",
      presente: 0,
      pendientes: [],
    },
  ],
  personal: [
    {
      id: 1,
      nombre: "Pepito Andrés Perez Roa",
      documento: "1023456789",
      cargo: "Operario",
      obra: "Mandarino",
      estado: "activo",
      correo: "pepito@ejemplo.com",
      telefono: "3001112233",
    },
    {
      id: 2,
      nombre: "José Steven Peña",
      documento: "1023678901",
      cargo: "Encargado",
      obra: "H. Peñalisa",
      estado: "inactivo",
      correo: "jose@ejemplo.com",
      telefono: "3002223344",
    },
    {
      id: 3,
      nombre: "Javier Esteban Rendón",
      documento: "1023000000",
      cargo: "Inspector SST",
      obra: "H. Nakare",
      estado: "activo",
      correo: "javier@ejemplo.com",
      telefono: "3003334455",
    },
    {
      id: 4,
      nombre: "Manuel Gámez",
      documento: "1099999999",
      cargo: "Operario",
      obra: "Mandarino",
      estado: "activo",
      correo: "manuel@ejemplo.com",
      telefono: "3004445566",
    },
    {
      id: 5,
      nombre: "Jesus Alberto de Agua",
      documento: "1088888888",
      cargo: "Operario",
      obra: "H. Peñalisa",
      estado: "activo",
      correo: "jesus@ejemplo.com",
      telefono: "3005556677",
    },
    {
      id: 6,
      nombre: "Julio Sanchez",
      documento: "1023555777",
      cargo: "Operario",
      obra: "Mandarino",
      estado: "activo",
      correo: "julio@ejemplo.com",
      telefono: "3007771234",
    },
    {
      id: 7,
      nombre: "Felipe Ríos",
      documento: "1034555011",
      cargo: "Operario",
      obra: "Edificio Torre Central",
      estado: "activo",
      correo: "felipe@ejemplo.com",
      telefono: "3008882233",
    },
    {
      id: 8,
      nombre: "Angela Buitrago",
      documento: "1023222111",
      cargo: "Inspector SST",
      obra: "Hospital Regional",
      estado: "inactivo",
      correo: "angela@ejemplo.com",
      telefono: "3010010010",
    },
    {
      id: 9,
      nombre: "Laura Martinez",
      documento: "1010101010",
      cargo: "Encargado",
      obra: "Bodega Industrial Sur",
      estado: "activo",
      correo: "laura@ejemplo.com",
      telefono: "3011011011",
    },
    {
      id: 10,
      nombre: "Daniel Quintero",
      documento: "1011223344",
      cargo: "Operario",
      obra: "H. Nakare",
      estado: "activo",
      correo: "daniel@ejemplo.com",
      telefono: "3012211000",
    },
    {
      id: 11,
      nombre: "Santiago Lopez",
      documento: "1020304050",
      cargo: "Operario",
      obra: "H. Peñalisa",
      estado: "activo",
      correo: "santiago@ejemplo.com",
      telefono: "3013322110",
    },
    {
      id: 12,
      nombre: "Carolina Parra",
      documento: "1122334455",
      cargo: "Inspector SST",
      obra: "Mandarino",
      estado: "activo",
      correo: "carolina@ejemplo.com",
      telefono: "3014433221",
    },
  ],
  usuarios: [
    { id: 1, nombre: "Sofía Beltrán Hoyuela", correo: "sofia@gmail.com", password: "", rol: "Administrador", obra: "Mandarino", estado: "Inactivo" },
    { id: 2, nombre: "Sandra Milena García", correo: "sandra@gmail.com", password: "", rol: "Inspector SST", obra: "H. Peñalisa", estado: "Activo" },
    { id: 3, nombre: "Mauricio Javier Torres", correo: "mauricio@gmail.com", password: "", rol: "Encargado", obra: "H. Nakare", estado: "Activo" },
    { id: 4, nombre: "Edwin Fernando Castro", correo: "edwin@gmail.com", password: "", rol: "Administrador", obra: "Mandarino", estado: "Inactivo" },
    { id: 5, nombre: "Diana Lorena Fernandez", correo: "diana@gmail.com", password: "", rol: "Inspector SST", obra: "H. Peñalisa", estado: "Activo" },
    { id: 6, nombre: "Oscar Gomez Estrada", correo: "oscar@gmail.com", password: "", rol: "Encargado", obra: "H. Nakare", estado: "Activo" },
    { id: 7, nombre: "Claudia Yulieth Faca", correo: "claudia@gmail.com", password: "", rol: "Administrador", obra: "H. Peñalisa", estado: "Activo" },
    { id: 8, nombre: "Pedro Jose Castillo", correo: "pedro@gmail.com", password: "", rol: "Inspector SST", obra: "H. Nakare", estado: "Activo" },
  ],
  dispositivos: [
    { id: "D1", nombre: "Portátil Mandarino", tipo: "Portátil", obra: "Mandarino", ultimoAcceso: "17/02/2025 19:30", estado: "Inactivo", pin: "1234" },
    { id: "D2", nombre: "Portátil H.Peñalisa", tipo: "Portátil", obra: "H. Peñalisa", ultimoAcceso: "Ayer 19:24", estado: "Activo", pin: "5678" },
    { id: "D3", nombre: "Tablet H. Nakare", tipo: "Tablet", obra: "H. Nakare", ultimoAcceso: "Hoy 6:10", estado: "Activo", pin: "9012" },
  ],
  asistencias: [
    { id: 1, trabajadorId: 1, nombre: "Pepito Andres Perez Roa", obra: "Mandarino", fecha: "2026-04-11", ingreso: "6:00", salida: "18:00", estado: "Salida", tipo: "Normal" },
    { id: 2, trabajadorId: 2, nombre: "Jose Steven Peña Hernan.", obra: "H. Peñalisa", fecha: "2026-04-11", ingreso: "5:30", salida: "17:56", estado: "Salida", tipo: "Normal" },
    { id: 3, trabajadorId: 3, nombre: "Javier Esteban Rendón R.", obra: "H. Nakare", fecha: "2026-04-11", ingreso: "5:45", salida: "", estado: "Presente", tipo: "Normal" },
    { id: 4, trabajadorId: 4, nombre: "Manuel Esteban Gámez", obra: "Mandarino", fecha: "2026-04-11", ingreso: "", salida: "", estado: "Ausente", tipo: "Normal" },
    { id: 5, trabajadorId: 5, nombre: "Jesus Alberto de Agua Gar.", obra: "H. Peñalisa", fecha: "2026-06-11", ingreso: "6:10", salida: "19:00", estado: "Salida", tipo: "Normal" },
    { id: 6, trabajadorId: 6, nombre: "Julio Sanchez", obra: "Mandarino", fecha: "2026-05-11", ingreso: "6:08", salida: "", estado: "Presente", tipo: "Permiso" },
    { id: 7, trabajadorId: 10, nombre: "Daniel Quintero", obra: "H. Nakare", fecha: "2026-05-11", ingreso: "", salida: "", estado: "Ausente", tipo: "Incapacidad" },
    { id: 8, trabajadorId: 11, nombre: "Santiago Lopez", obra: "H. Peñalisa", fecha: "2026-05-11", ingreso: "5:55", salida: "17:40", estado: "Salida", tipo: "Normal" },
  ],
  documentos: [
    { id: 1, trabajadorId: 1, trabajador: "Pepito Andres Perez Roa", tipo: "Examen médico", emision: "2025-06-30", vencimiento: "2026-08-30", archivoUrl: "examen_pepito.pdf" },
    { id: 2, trabajadorId: 2, trabajador: "Jose Steven Peña Hernan", tipo: "Curso de alturas", emision: "2024-10-27", vencimiento: "2026-04-27", archivoUrl: "alturas_jose.pdf" },
    { id: 3, trabajadorId: 3, trabajador: "Javier Esteban Rendón", tipo: "Examen médico", emision: "2025-04-10", vencimiento: "2025-04-10", archivoUrl: "examen_javier.pdf" },
    { id: 4, trabajadorId: 4, trabajador: "Manuel Gámez", tipo: "Carné de manipulación", emision: "2025-01-15", vencimiento: "2026-12-20", archivoUrl: "carnet_manuel.pdf" },
    { id: 5, trabajadorId: 5, trabajador: "Jesus Alberto de Agua", tipo: "Examen médico", emision: "2024-06-01", vencimiento: "2026-05-15", archivoUrl: "examen_jesus.pdf" },
    { id: 6, trabajadorId: 1, trabajador: "Pepito Andres Perez Roa", tipo: "Curso de alturas", emision: "2023-08-01", vencimiento: "2026-04-20", archivoUrl: "alturas_pepito.pdf" },
  ],
};
