/**
 * Estado en memoria compartido entre servicios (sin base de datos).
 * Cada servicio importa este módulo para lecturas/escrituras consistentes
 * (obras, personal, asistencias, etc.). Cuando exista API, sustituir por llamadas HTTP.
 */

export const store = {
  nextIds: {
    obra: 5,
    personal: 6,
    usuario: 7,
    dispositivo: 4,
    asistencia: 9,
    documento: 7,
  },
  obras: [
    {
      id: 1,
      nombre: "Mandarino",
      ubicacion: "Bogotá, Av. Caracas",
      encargado: "Mauricio Javier Torres",
      fechaInicio: "2024-01-15",
      estado: "activa",
    },
    {
      id: 2,
      nombre: "H. Peñalisa",
      ubicacion: "Ibagué",
      encargado: "Mauricio Javier Torres",
      fechaInicio: "2023-08-01",
      estado: "activa",
    },
    {
      id: 3,
      nombre: "H. Nakare",
      ubicacion: "Bogotá, Suba",
      encargado: "Mauricio Javier Torres",
      fechaInicio: "2024-03-10",
      estado: "suspendida",
    },
    {
      id: 4,
      nombre: "Proyecto Norte",
      ubicacion: "Tunja",
      encargado: "Mauricio Javier Torres",
      fechaInicio: "2022-11-01",
      estado: "finalizada",
    },
  ],
  personal: [
    {
      id: 1,
      nombre: "Pepito Andrés Perez Roa",
      documento: "1023456789",
      cargo: "Operario",
      obra: "Mandarino",
      estado: "activo",
      correo: "pepito@ejemplo.com",
      telefono: "3001112233",
    },
    {
      id: 2,
      nombre: "José Steven Peña",
      documento: "1023678901",
      cargo: "Oficial",
      obra: "H. Peñalisa",
      estado: "inactivo",
      correo: "jose@ejemplo.com",
      telefono: "3002223344",
    },
    {
      id: 3,
      nombre: "Javier Esteban Rendón",
      documento: "1023000000",
      cargo: "Operario",
      obra: "H. Nakare",
      estado: "activo",
      correo: "javier@ejemplo.com",
      telefono: "3003334455",
    },
    {
      id: 4,
      nombre: "Manuel Gámez",
      documento: "1099999999",
      cargo: "Maestro",
      obra: "Mandarino",
      estado: "activo",
      correo: "manuel@ejemplo.com",
      telefono: "3004445566",
    },
    {
      id: 5,
      nombre: "Jesus Alberto de Agua",
      documento: "1088888888",
      cargo: "Operario",
      obra: "H. Peñalisa",
      estado: "activo",
      correo: "jesus@ejemplo.com",
      telefono: "3005556677",
    },
  ],
  usuarios: [
    { id: 1, nombre: "Sofía Beltrán Hoyuela", correo: "sofia@gmail.com", password: "", rol: "Administrador", obra: "Mandarino", estado: "Activo" },
    { id: 2, nombre: "Sandra Milena García", correo: "sandra@gmail.com", password: "", rol: "Inspector SST", obra: "H. Peñalisa", estado: "Activo" },
    { id: 3, nombre: "Mauricio Javier Torres", correo: "mauricio@gmail.com", password: "", rol: "Encargado", obra: "H. Nakare", estado: "Activo" },
    { id: 4, nombre: "Edwin Fernando Castro", correo: "edwin@gmail.com", password: "", rol: "Administrador", obra: "H. Nakare", estado: "Inactivo" },
    { id: 5, nombre: "Claudia Yulieth Faca", correo: "claudia@megaconstrucciones.com", password: "", rol: "Administrador", obra: "Mandarino", estado: "Activo" },
    { id: 6, nombre: "Diana Fernández", correo: "diana@ejemplo.com", password: "", rol: "Inspector SST", obra: "Mandarino", estado: "Activo" },
  ],
  dispositivos: [
    { id: "DEV-001", nombre: "Portátil Mandarino", tipo: "Portátil", obra: "Mandarino", ultimoAcceso: "2025-02-17T19:30:00", estado: "Inactivo", pin: "1234" },
    { id: "DEV-002", nombre: "Portátil H.Peñalisa", tipo: "Portátil", obra: "H. Peñalisa", ultimoAcceso: "2026-05-03T19:24:00", estado: "Activo", pin: "5678" },
    { id: "DEV-003", nombre: "Tablet H. Nakare", tipo: "Tablet", obra: "H. Nakare", ultimoAcceso: "2026-05-04T06:10:00", estado: "Activo", pin: "9012" },
  ],
  asistencias: [
    { id: 1, trabajadorId: 1, nombre: "Pepito Andrés Perez Roa", obra: "Mandarino", fecha: "2026-04-11", ingreso: "06:00", salida: "18:00", estado: "Salida" },
    { id: 2, trabajadorId: 2, nombre: "José Steven Peña", obra: "H. Peñalisa", fecha: "2026-04-11", ingreso: "05:30", salida: "17:56", estado: "Salida" },
    { id: 3, trabajadorId: 3, nombre: "Javier Esteban Rendón", obra: "H. Nakare", fecha: "2026-04-11", ingreso: "05:45", salida: "", estado: "Presente" },
    { id: 4, trabajadorId: 4, nombre: "Manuel Gámez", obra: "Mandarino", fecha: "2026-04-11", ingreso: "", salida: "", estado: "Ausente" },
    { id: 5, trabajadorId: 5, nombre: "Jesus Alberto de Agua", obra: "H. Peñalisa", fecha: "2026-04-06", ingreso: "06:10", salida: "19:00", estado: "Salida" },
    { id: 6, trabajadorId: 1, nombre: "Pepito Andrés Perez Roa", obra: "Mandarino", fecha: "2026-04-10", ingreso: "06:00", salida: "17:00", estado: "Salida" },
    { id: 7, trabajadorId: 3, nombre: "Javier Esteban Rendón", obra: "H. Nakare", fecha: "2026-04-10", ingreso: "05:50", salida: "18:10", estado: "Salida" },
    { id: 8, trabajadorId: 2, nombre: "José Steven Peña", obra: "H. Peñalisa", fecha: "2026-04-09", ingreso: "", salida: "", estado: "Ausente" },
  ],
  documentos: [
    { id: 1, trabajadorId: 1, trabajador: "Pepito Andres Perez Roa", tipo: "Examen médico", emision: "2025-06-30", vencimiento: "2026-08-30", archivoUrl: "examen_pepito.pdf" },
    { id: 2, trabajadorId: 2, trabajador: "Jose Steven Peña Hernan", tipo: "Curso de alturas", emision: "2024-10-27", vencimiento: "2026-04-27", archivoUrl: "alturas_jose.pdf" },
    { id: 3, trabajadorId: 3, trabajador: "Javier Esteban Rendón", tipo: "Examen médico", emision: "2025-04-10", vencimiento: "2025-04-10", archivoUrl: "examen_javier.pdf" },
    { id: 4, trabajadorId: 4, trabajador: "Manuel Gámez", tipo: "Carné de manipulación", emision: "2025-01-15", vencimiento: "2026-12-20", archivoUrl: "carnet_manuel.pdf" },
    { id: 5, trabajadorId: 5, trabajador: "Jesus Alberto de Agua", tipo: "Examen médico", emision: "2024-06-01", vencimiento: "2026-05-15", archivoUrl: "examen_jesus.pdf" },
    { id: 6, trabajadorId: 1, trabajador: "Pepito Andres Perez Roa", tipo: "Curso de alturas", emision: "2023-08-01", vencimiento: "2026-04-20", archivoUrl: "alturas_pepito.pdf" },
  ],
};
