/**
 * Estado en memoria compartido entre servicios (sin base de datos).
 * Cada servicio importa este modulo para lecturas/escrituras consistentes.
 */
export const store = {
  nextIds: {
    obra: 6,
    personal: 13,
    usuario: 9,
    dispositivo: 4,
    asistencia: 9,
    documento: 7,
    novedad: 5,
  },
  config: {
    empresa: {
      nombre: "Mega Construcciones Jimenez SAS",
      nit: "900.123.123-0",
      correo: "admin@megaconstrucciones.com",
      telefono: "+57 313 1234567",
    },
    horario: { inicio: "06:00", cierre: "18:00" },
    notificaciones: {
      ausencias: true,
      dispositivos: true,
      reportes: false,
      novedades: true,
      biometria: true,
    },
  },
  perfil: {
    nombre: "Claudia",
    apellido: "Yulieth Faca",
    documento: "1020195123",
    correo: "claudia@megaconstrucciones.com",
    telefono: "+57 313 1234567",
    rol: "Administrador",
    ultimoAcceso: "Hoy 8:30 AM",
    estado: "Activo",
    actividad: { obras: 30, reportes: 20, usuarios: 15 },
    empresaNombre: "Mega Construcciones Jiménez SAS",
  },
  novedades: [
    {
      id: 1,
      trabajador: "Juan Perez",
      cargo: "Operario",
      obra: "H. Peñalisa",
      registradoPor: "Diana Fernandez (Inspector SST)",
      estado: "Pendiente",
      tipo: "Novedad",
      subTipo: "Permiso médico",
      fecha: "25/04/2026",
      dias: 1,
      adjunto: "Orden_medica_perez.juan",
      motivoRechazo: "",
    },
    {
      id: 2,
      trabajador: "Jose Manuel Peña",
      cargo: "Operario",
      obra: "H. Peñalisa",
      registradoPor: "Oscar Gomez (Encargado)",
      estado: "Pendiente",
      tipo: "Traspaso",
      fecha: "25/04/2026",
      origen: "H. Peñalisa",
      destino: "H. Nakare",
      adjunto: null,
      motivoRechazo: "",
    },
    {
      id: 3,
      trabajador: "Juan Perez",
      cargo: "Operario",
      obra: "H. Peñalisa",
      registradoPor: "Diana Fernandez (Inspector SST)",
      estado: "Pendiente",
      tipo: "Novedad",
      subTipo: "Permiso médico",
      fecha: "25/06/2026",
      dias: 1,
      adjunto: "Orden_medica_perez.juan",
      motivoRechazo: "",
    },
    {
      id: 4,
      trabajador: "Oscar Acosta",
      cargo: "Operario",
      obra: "H. Nakare",
      registradoPor: "Oscar Gomez (Encargado)",
      estado: "Pendiente",
      tipo: "Traspaso",
      fecha: "25/04/2025",
      origen: "H. Peñalisa",
      destino: "H. Nakare",
      adjunto: null,
      motivoRechazo: "",
    },
  ],
  obras: [
    { id: "26IBG03", nombre: "Mandarino", ubicacion: "Ibagué", estado: "activa", personal: 50, presente: 0 },
    { id: "08001", nombre: "Edificio Torre Central", ubicacion: "Bogotá", estado: "activa", personal: 0, presente: 0 },
    { id: "08002", nombre: "Conjunto Residencial Norte", ubicacion: "Medellín", estado: "activa", personal: 0, presente: 0 },
    { id: "08003", nombre: "Centro Comercial Plaza", ubicacion: "Cali", estado: "activa", personal: 0, presente: 0 },
    { id: "08004", nombre: "Bodega Industrial Sur", ubicacion: "Bogotá", estado: "finalizada", personal: 0, presente: 0 },
    { id: "08005", nombre: "Hospital Regional", ubicacion: "Bucaramanga", estado: "suspendida", personal: 0, presente: 0 },
  ],
  personal: [
    { id: 1, nombre: "Pepito Andrés Perez Roa", documento: "1023456789", cargo: "Operario", obra: "Mandarino", estado: "activo", correo: "pepito@ejemplo.com", telefono: "3001112233" },
    { id: 2, nombre: "José Steven Peña", documento: "1023678901", cargo: "Encargado", obra: "Edificio Torre Central", estado: "inactivo", correo: "jose@ejemplo.com", telefono: "3002223344" },
    { id: 3, nombre: "Javier Esteban Rendón", documento: "1023000000", cargo: "Inspector SST", obra: "Conjunto Residencial Norte", estado: "activo", correo: "javier@ejemplo.com", telefono: "3003334455" },
    { id: 4, nombre: "Manuel Gámez", documento: "1099999999", cargo: "Operario", obra: "Mandarino", estado: "activo", correo: "manuel@ejemplo.com", telefono: "3004445566" },
    { id: 5, nombre: "Jesus Alberto de Agua", documento: "1088888888", cargo: "Operario", obra: "Edificio Torre Central", estado: "activo", correo: "jesus@ejemplo.com", telefono: "3005556677" },
    { id: 6, nombre: "Julio Sanchez", documento: "1023555777", cargo: "Operario", obra: "Mandarino", estado: "activo", correo: "julio@ejemplo.com", telefono: "3007771234" },
    { id: 7, nombre: "Felipe Ríos", documento: "1034555011", cargo: "Operario", obra: "Edificio Torre Central", estado: "activo", correo: "felipe@ejemplo.com", telefono: "3008882233" },
    { id: 8, nombre: "Angela Buitrago", documento: "1023222111", cargo: "Inspector SST", obra: "Hospital Regional", estado: "inactivo", correo: "angela@ejemplo.com", telefono: "3010010010" },
    { id: 9, nombre: "Laura Martinez", documento: "1010101010", cargo: "Encargado", obra: "Bodega Industrial Sur", estado: "activo", correo: "laura@ejemplo.com", telefono: "3011011011" },
    { id: 10, nombre: "Daniel Quintero", documento: "1011223344", cargo: "Operario", obra: "Conjunto Residencial Norte", estado: "activo", correo: "daniel@ejemplo.com", telefono: "3012211000" },
    { id: 11, nombre: "Santiago Lopez", documento: "1020304050", cargo: "Operario", obra: "Edificio Torre Central", estado: "activo", correo: "santiago@ejemplo.com", telefono: "3013322110" },
    { id: 12, nombre: "Carolina Parra", documento: "1122334455", cargo: "Inspector SST", obra: "Mandarino", estado: "activo", correo: "carolina@ejemplo.com", telefono: "3014433221" },
  ],
  usuarios: [
    { id: 1, nombre: "Sofía Beltrán Hoyuela", correo: "sofia@gmail.com", password: "", rol: "Administrador", obra: "Mandarino", estado: "Inactivo" },
    { id: 2, nombre: "Sandra Milena García", correo: "sandra@gmail.com", password: "", rol: "Inspector SST", obra: "Edificio Torre Central", estado: "Activo" },
    { id: 3, nombre: "Mauricio Javier Torres", correo: "mauricio@gmail.com", password: "", rol: "Encargado", obra: "Conjunto Residencial Norte", estado: "Activo" },
    { id: 4, nombre: "Edwin Fernando Castro", correo: "edwin@gmail.com", password: "", rol: "Administrador", obra: "Mandarino", estado: "Inactivo" },
    { id: 5, nombre: "Diana Lorena Fernandez", correo: "diana@gmail.com", password: "", rol: "Inspector SST", obra: "Edificio Torre Central", estado: "Activo" },
    { id: 6, nombre: "Oscar Gomez Estrada", correo: "oscar@gmail.com", password: "", rol: "Encargado", obra: "Conjunto Residencial Norte", estado: "Activo" },
    { id: 7, nombre: "Claudia Yulieth Faca", correo: "claudia@gmail.com", password: "", rol: "Administrador", obra: "Edificio Torre Central", estado: "Activo" },
    { id: 8, nombre: "Pedro Jose Castillo", correo: "pedro@gmail.com", password: "", rol: "Inspector SST", obra: "Conjunto Residencial Norte", estado: "Activo" },
  ],
  dispositivos: [
    { id: "D1", nombre: "Portátil Mandarino", tipo: "Portátil", obra: "Mandarino", ultimoAcceso: "17/02/2025 19:30", estado: "Inactivo", pin: "1234" },
    { id: "D2", nombre: "Portátil Torre Central", tipo: "Portátil", obra: "Edificio Torre Central", ultimoAcceso: "Ayer 19:24", estado: "Activo", pin: "5678" },
    { id: "D3", nombre: "Tablet Res. Norte", tipo: "Tablet", obra: "Conjunto Residencial Norte", ultimoAcceso: "Hoy 6:10", estado: "Activo", pin: "9012" },
  ],
  asistencias: [
    { id: 1, trabajadorId: 1, nombre: "Pepito Andres Perez Roa", obra: "Mandarino", fecha: "11/04/2026", ingreso: "6:00", salida: "18:00", estado: "Salida", tipo: "Normal" },
    { id: 2, trabajadorId: 2, nombre: "Jose Steven Peña Hernandez", obra: "Edificio Torre Central", fecha: "11/04/2026", ingreso: "5:30", salida: "17:56", estado: "Salida", tipo: "Normal" },
    { id: 3, trabajadorId: 3, nombre: "Javier Esteban Rendón R.", obra: "Conjunto Residencial Norte", fecha: "11/04/2026", ingreso: "5:45", salida: null, estado: "Presente", tipo: "Normal" },
    { id: 4, trabajadorId: 4, nombre: "Manuel Esteban Gámez", obra: "Mandarino", fecha: "11/04/2026", ingreso: null, salida: null, estado: "Ausente", tipo: "Normal" },
    { id: 5, trabajadorId: 5, nombre: "Jesus Alberto de Agua Garcia", obra: "Edificio Torre Central", fecha: "11/06/2026", ingreso: "6:10", salida: "19:00", estado: "Salida", tipo: "Normal" },
    { id: 6, trabajadorId: 8, nombre: "Diana Lorena Fernandez", obra: "Mandarino", fecha: "11/04/2026", ingreso: "7:00", salida: "16:00", estado: "Salida", tipo: "Normal" },
    { id: 7, trabajadorId: 10, nombre: "Oscar Gomez Estrada", obra: "Conjunto Residencial Norte", fecha: "11/04/2026", ingreso: "6:30", salida: null, estado: "Presente", tipo: "Permiso" },
    { id: 8, trabajadorId: 11, nombre: "Sandra Milena Garcia", obra: "Edificio Torre Central", fecha: "11/04/2026", ingreso: null, salida: null, estado: "Ausente", tipo: "Incapacidad" },
  ],
  documentos: [
    { id: 1, trabajadorId: 1, trabajador: "Pepito Andres Perez Roa", tipo: "Examen médico", emision: "2025-06-30", vencimiento: "2026-06-30", archivoUrl: "examen_pepito.pdf" },
    { id: 2, trabajadorId: 2, trabajador: "Jose Steven Peña Hernan.", tipo: "Curso de alturas", emision: "2024-10-27", vencimiento: "2026-04-27", archivoUrl: "alturas_jose.pdf" },
    { id: 3, trabajadorId: 3, trabajador: "Javier Esteban Rendón R.", tipo: "Examen médico", emision: "2025-04-10", vencimiento: "2025-04-10", archivoUrl: "examen_javier.pdf" },
    { id: 4, trabajadorId: 1, trabajador: "Pepito Andres Perez Roa", tipo: "Examen médico", emision: "2025-06-30", vencimiento: "2026-06-30", archivoUrl: "examen_pepito.pdf" },
    { id: 5, trabajadorId: 2, trabajador: "Jose Steven Peña Hernan.", tipo: "Curso de alturas", emision: "2024-10-27", vencimiento: "2026-04-27", archivoUrl: "alturas_jose.pdf" },
    { id: 6, trabajadorId: 3, trabajador: "Javier Esteban Rendón R.", tipo: "Examen médico", emision: "2025-04-10", vencimiento: "2025-04-10", archivoUrl: "examen_javier.pdf" },
  ],
};
